### ISSUE TITLE
Feature request: ability to set local path as destination

### ISSUE THREAD

**Issue by cellvia** [IonicaBizau/gpm#20]
Would be awesome to be able to run this using a local path or if none supplied, the CWD

**Comment by IonicaBizau** [comment]
@cellvia Is `--destination .` what you're looking for?

**Comment by cellvia** [comment]
no, sorry, i meant for "input"  it accepts npm package or git url, but would be cool to be able to point it at a subfolder or CWD (assumes there is a package.json in the folder in question)

**Comment by IonicaBizau** [comment]
@cellvia To install the dependencies of a `package.json`, you just need `gpm -i .`

**Comment by IonicaBizau** [comment]
In `3.x.x` we can set a custom `node_modules` folder.
