### ISSUE TITLE
Support repositories with URLs containing multiple schemes

### ISSUE THREAD

**Issue by nihey** [IonicaBizau/gpm#3]
I noticed there is a particular package that causes `gpm` to fail: `mkdirp`. It caused this error:

```
progress Clonning git+https://github.com/substack/node-mkdirp.git
error Command failed: /bin/sh -c git clone "git+https://github.com/substack/node-mkdirp.git" "."
```

Looking upon their [registry](http://registry.npmjs.org/mkdirp), I noticed their URLs really contained the 'git+https' scheme.

I don't know if that kind of URL is actually correct, but supporting it may only require some changes [here](https://github.com/IonicaBizau/node-gpm/blob/master/lib/index.js#L112).

**Comment by IonicaBizau** [comment]
This should be fixed in `git-url-parse`. See https://github.com/IonicaBizau/node-git-url-parse/issues/8.

**Comment by IonicaBizau** [comment]
The issue I listed above is now fixed: https://github.com/IonicaBizau/node-git-url-parse/issues/8

Contributions are more than welcome! If I'm not wrong, just an upgrade should fix the problem. :sparkle:

**Comment by nihey** [comment]
Nice work. If this is not so urgent, I can look after it on the next weekend.

Just to be sure, when having multiple protocols, such as `git` or `https`, we should probably stick to the `git` one, right?

**Comment by IonicaBizau** [comment]
>  I can look after it on the next weekend.

Perfect! :star2: 

> Just to be sure, when having multiple protocols, such as git or https, we should probably stick to the git one, right?

Well, that's module logic. There are two fields: `protocols` (array, all protocols) and `protocol` (string, for convenience, the first element of `protocols` or `ssh` if ssh is detected). This is handled in [`git-up`](https://github.com/IonicaBizau/node-git-up#gitupinput).

Calling `toString("git")` or `toString("ssh")` is enough, here, I think. :balloon:
